#!/usr/bin/env python3
"""Offline ArkOS Pinyin lexicon compilation from pinned Rime/OpenCC data."""
from pathlib import Path
import json,math,hashlib
root=Path('third_party/rime-data')
def pairs(path):
 for line in path.read_text().splitlines():
  if line.startswith('#') or '\t' not in line:continue
  yield line.split('\t')
char_map={a:b.split()[0] for a,b,*_ in pairs(root/'opencc/TSCharacters.txt')}
phrase_map={a:b.split()[0] for a,b,*_ in pairs(root/'opencc/TSPhrases.txt')}
def simp(text):return phrase_map.get(text,''.join(char_map.get(c,c) for c in text))
readings={};exact={}
for row in pairs(root/'rime-luna-pinyin/luna_pinyin.dict.yaml'):
 text,key,*weight=row;parts=key.split();key=''.join(parts)
 if not key.isascii() or not key.isalpha() or len(key)>48:continue
 text=simp(text)
 if not all(0x4e00<=ord(c)<=0x9fff for c in text):continue
 if len(parts)!=len(text):continue
 if len(text)==1:readings.setdefault(text,parts[0])
 else:exact.setdefault(text,parts)
# Prefer the fixed Unicode kMandarin reading where a syllable is shared.
pinyin_data=Path('user/pinyin_data.h').read_text()
import re
chars=re.search(r'pinyin_characters\[\].*?=\s*(.*?);',pinyin_data,re.S).group(1)
chars=''.join(json.loads(t) for t in re.findall(r'"(?:[^"\\]|\\.)*"',chars)).encode()
for key,off,count in re.findall(r'\{"([a-z]+)",(\d+),(\d+)\}',pinyin_data):
 for i in range(int(count)):
  c=chars[int(off)+i*3:int(off)+(i+1)*3].decode();readings.setdefault(c,key)
freq={}
for text,value,*_ in pairs(root/'rime-essay/essay.txt'):
 text=simp(text)
 if 1<=len(text)<=12 and all(0x4e00<=ord(c)<=0x9fff for c in text):freq[text]=max(freq.get(text,0),int(value))
words=sorted(((w,f) for w,f in freq.items() if f>=5 and 2<=len(w)<=12),key=lambda p:-p[1])[:80000]
lex={}
def insert(text,parts,frequency):
 key=''.join(parts)
 if len(key)>48:return
 boundary=0;offset=0
 for part in parts[:-1]:offset+=len(part);boundary|=1<<offset
 cost=max(1,int((math.log(20000000/max(1,frequency))+2.4)*256))
 item=(key,text,boundary);lex[item]=min(lex.get(item,65535),cost)
for c,key in readings.items():insert(c,[key],freq.get(c,1))
for w,f in words:
 parts=exact.get(w) or [readings.get(c) for c in w]
 if all(parts):insert(w,parts,f)
for w,parts in exact.items():
 if len(w)<=12:insert(w,parts,freq.get(w,10))
# Preserve all alternative character readings.
for row in pairs(root/'rime-luna-pinyin/luna_pinyin.dict.yaml'):
 text,key,*_=row;text=simp(text)
 if len(text)==1 and text in readings and key.isascii() and key.isalpha():insert(text,[key],freq.get(text,1))
keys=bytearray();texts=bytearray();key_offsets={};text_offsets={};rows=[]
for (key,text,boundary),cost in sorted(lex.items(),key=lambda item:(item[0][0],item[1],item[0][1])):
 if key not in key_offsets:key_offsets[key]=len(keys);keys+=key.encode()+b'\0'
 if text not in text_offsets:text_offsets[text]=len(texts);texts+=text.encode()+b'\0'
 rows.append((key_offsets[key],text_offsets[text],cost,len(key),len(text),boundary))
with Path('user/ime_lexicon.h').open('w') as out:
 out.write('/* Generated by scripts/generate-ime.py from pinned LGPL-3.0 Rime data. */\n')
 out.write('typedef struct {uint32_t key,text;uint16_t cost;uint8_t length,characters;uint64_t boundaries;} ImeLexeme;\n')
 for name,data in [('ime_keys',keys),('ime_texts',texts)]:
  out.write('static const char '+name+'[]=\n')
  for at in range(0,len(data),80):out.write('"'+''.join('\\%03o'%c for c in data[at:at+80])+'"\n')
  out.write(';\n')
 out.write('static const ImeLexeme ime_lexicon[]={\n')
 for row in rows:out.write('{%s},\n'%','.join(str(x)+('ull' if i==5 else '') for i,x in enumerate(row)))
 out.write('};\n')
report={'entries':len(rows),'key_bytes':len(keys),'text_bytes':len(texts),'words_requested':len(words),'sha256':hashlib.sha256(Path('user/ime_lexicon.h').read_bytes()).hexdigest()}
(root/'generated.json').write_text(json.dumps(report,indent=2)+'\n');print(report)
