#!/usr/bin/env python3
"""Reproducible standard WASM fixtures; no assembler/network build dependency.
Every valid fixture is also validated/executed by the independent Node engine in
 tests/wasm_oracle.js (development only). Binary format: W3C Core specification.
"""
from pathlib import Path
import json,struct
ROOT=Path(__file__).resolve().parents[1]
def u(n):
 b=[]
 while True:
  v=n&127;n>>=7;b.append(v|(128 if n else 0))
  if not n:return bytes(b)
def s(n):
 b=[]
 while True:
  v=n&127;n>>=7;done=(n==0 and not v&64) or (n==-1 and v&64);b.append(v if done else v|128)
  if done:return bytes(b)
def name(x):b=x.encode();return u(len(b))+b
def vec(xs):return u(len(xs))+b''.join(xs)
def ty(params=b'',rets=b''):return b'\x60'+u(len(params))+params+u(len(rets))+rets
def sec(i,b):return bytes([i])+u(len(b))+b
def icon(n):return b'\x41'+s(n)
def module(types,bodies,indices,imports=(),memory=None,data=b'',table=False,globals_=b'',export_index=None):
 out=b'\0asm\1\0\0\0'+sec(1,vec(types))
 if imports:out+=sec(2,vec([name(a)+name(b)+b'\0'+u(c) for a,b,c in imports]))
 out+=sec(3,vec([u(i) for i in indices]))
 if table:out+=sec(4,b'\x01\x70\x00\x01')
 if memory is not None:out+=sec(5,b'\x01\x01'+u(memory)+u(64))
 if globals_:out+=sec(6,globals_)
 ex=[name('main')+b'\0'+u(len(imports)+len(bodies)-1 if export_index is None else export_index)]
 if memory is not None:ex.append(name('memory')+b'\x02\x00')
 out+=sec(7,vec(ex))
 if table:out+=sec(9,b'\x01\x00\x41\x00\x0b\x01\x00')
 out+=sec(10,vec([u(len(b))+b for b in bodies]))
 if data:out+=sec(11,b'\x01\x00\x41\x00\x0b'+u(len(data))+data)
 return out
T=ty(rets=b'\x7f'); modules={};expected={}
def add(n,b,result=None,error=None):modules[n]=b;expected[n]={'result':result,'error':error}
msg='Hello from native ArkOS WASM! 中国 : ;\n'.encode()
add('hello',module([ty(b'\x7f\x7f'),T],[b'\0'+icon(0)+icon(len(msg))+b'\x10\0'+icon(42)+b'\x0b'],[1],[('ark','log',0)],1,msg),42)
fib=b'\0\x20\0'+icon(2)+b'\x48\x04\x7f\x20\0\x05\x20\0'+icon(1)+b'\x6b\x10\0\x20\0'+icon(2)+b'\x6b\x10\0\x6a\x0b\x0b'
add('fibonacci',module([ty(b'\x7f',b'\x7f'),T],[fib,b'\0'+icon(10)+b'\x10\0\x0b'],[0,1]),55)
add('memory',module([T],[b'\0'+icon(4)+icon(123)+b'\x36\x02\0'+icon(1)+b'\x40\0\x1a'+icon(4)+b'\x28\x02\0\x3f\0\x6a\x0b'],[0],memory=1),125)
add('grow_limit',module([T],[b'\0'+icon(65)+b'\x40\0\x0b'],[0],memory=1),-1)
add('float',module([T],[b'\0\x44'+struct.pack('<d',1.5)+b'\x44'+struct.pack('<d',2.5)+b'\xa0\xaa\x0b'],[0]),4)
add('round',module([T],[b'\0\x44'+struct.pack('<d',2.5)+b'\x9e\xaa\x0b'],[0]),2)
add('sqrt',module([T],[b'\0\x44'+struct.pack('<d',81)+b'\x9f\xaa\x0b'],[0]),9)
add('table',module([T],[b'\0'+icon(9)+b'\x0b',b'\0'+icon(0)+b'\x11\0\0\x0b'],[0,0],table=True),9)
add('global',module([T],[b'\0\x23\0'+icon(1)+b'\x6a\x24\0\x23\0\x0b'],[0],globals_=b'\x01\x7f\x01'+icon(5)+b'\x0b'),6)
iov=struct.pack('<II',16,len(msg))+bytes(8)+msg
add('wasi',module([ty(b'\x7f'*4,b'\x7f'),T],[b'\0'+icon(1)+icon(0)+icon(1)+icon(8)+b'\x10\0\x1a'+icon(8)+b'\x28\x02\0\x0b'],[1],[('wasi_snapshot_preview1','fd_write',0)],1,iov),len(msg))
add('wasi_exit',module([ty(b'\x7f'),T],[b'\0'+icon(7)+b'\x10\0'+icon(99)+b'\x0b'],[1],[('wasi_snapshot_preview1','proc_exit',0)]),None,'exit7')
add('out_of_bounds',module([T],[b'\0'+icon(65535)+b'\x28\x02\0\x0b'],[0],memory=1),None,'bounds')
add('divide_zero',module([T],[b'\0'+icon(8)+icon(0)+b'\x6d\x0b'],[0]),None,'divide')
add('loop',module([T],[b'\0\x03\x40\x0c\0\x0b'+icon(0)+b'\x0b'],[0]),None,'gas')
add('recursion',module([T],[b'\0\x10\0\x0b'],[0]),None,'stack')
add('bad_import',module([ty(),T],[b'\0'+icon(0)+b'\x0b'],[1],[('env','host_shell',0)]),None,'import')
add('bad_pointer',module([ty(b'\x7f\x7f'),T],[b'\0'+icon(-1)+icon(9)+b'\x10\0'+icon(0)+b'\x0b'],[1],[('ark','log',0)],1),None,'bounds')
add('invalid_type',module([T],[b'\0\x43'+struct.pack('<f',1)+b'\x0b',b'\0'+icon(0)+b'\x0b'],[0,0]),None,'type')
add('truncated',modules['hello'][:-1],None,'parse')
# Export scalar bit patterns to exercise freestanding float helpers independently.
for label,opcode,val,result in [('floor_neg',0x9c,-1.25,-2),('ceil_neg',0x9b,-1.25,-1),('trunc_neg',0x9d,-1.75,-1),('round_even',0x9e,-2.5,-2)]:
 add(label,module([T],[b'\0\x44'+struct.pack('<d',val)+bytes([opcode])+b'\xaa\x0b'],[0]),result)
out=ROOT/'examples/wasm';out.mkdir(parents=True,exist_ok=True)
for n,b in modules.items():(out/(n+'.wasm')).write_bytes(b)
(out/'expected.json').write_text(json.dumps(expected,indent=2)+'\n')
header=['/* Generated by scripts/make-wasm-examples.py. Standard WASM bytes. */']
for n in ['hello','fibonacci','memory','float','wasi','out_of_bounds','loop']:
 header.append('static const unsigned char wasm_'+n+'[]={'+','.join(str(x) for x in modules[n])+'};')
(ROOT/'runtime/wasm/examples.h').write_text('\n'.join(header)+'\n')
print('Generated',len(modules),'standard WASM fixtures')
